story:
  plot_generator:
    model: "gpt-4"
    max_tokens: 2000
    temperature: 0.7
    
  scene_planner:
    max_scenes: 50
    default_scene_duration: 10
    
  character_developer:
    max_characters: 20
    personality_depth: "detailed"
    
  dialogue_generator:
    style_matching: true
    emotion_tracking: true

visual:
  scene_interpreter:
    detail_level: "high"
    style_preservation: true
    
  image_generator:
    model: "stable-diffusion"
    resolution: "1920x1080"
    quality: "high"
    
  animation_controller:
    framerate: 60
    interpolation: "smooth"
    
audio:
  music_composer:
    quality: "high"
    format: "wav"
    sample_rate: 48000
    
  voice_generator:
    model: "neural-tts"
    quality: "high"
    emotion_support: true
    
  audio_mixer:
    channels: "stereo"
    bit_depth: 24
    normalization: true

quality:
  continuity_checker:
    strictness: "high"
    auto_fix: false
    
  content_moderator:
    guidelines: "standard"
    sensitivity: "medium" 